import { GunplaAnalysis, PaintRecommendation } from '@/types'

// ──────────────────────────────────────────────
//  Markdown Export (Notion 対応)
// ──────────────────────────────────────────────

export function generateMarkdown(analysis: GunplaAnalysis): string {
  const lines: string[] = []

  lines.push(`# ${analysis.kitName} — 塗装カラー分析`)
  lines.push('')
  lines.push(`> ${analysis.overallStyle}`)
  lines.push('')
  lines.push(`**分析日:** ${new Date().toLocaleDateString('ja-JP')}  `)
  lines.push(`**部位数:** ${analysis.blocks.length}`)
  lines.push('')
  lines.push('---')
  lines.push('')

  for (const block of analysis.blocks) {
    lines.push(`## ${block.blockName}`)
    lines.push('')

    const currentColorList = block.currentColors
      .map((c) => `\`${c.hex}\` ${c.name}`)
      .join(' / ')
    lines.push(`**現在の色:** ${currentColorList}`)
    lines.push('')

    for (const rec of block.recommendations) {
      const typeLabel = rec.type === 'change' ? '変更' : rec.type === 'add' ? '追加' : 'アクセント'
      lines.push(`### [${typeLabel}] ${rec.description}`)
      lines.push('')

      if (rec.from) {
        lines.push(`- **Before:** \`${rec.from.hex}\` ${rec.from.name}`)
      }
      lines.push(`- **After:** \`${rec.to.hex}\` ${rec.to.name}`)
      lines.push('')
      lines.push('**調色レシピ**')
      lines.push('')
      lines.push('```')
      lines.push(rec.recipe)
      lines.push('```')
      lines.push('')
      lines.push(`*${rec.effect}*`)
      lines.push('')
    }

    lines.push('---')
    lines.push('')
  }

  lines.push('*Generated by ガンプラ塗装カラーアドバイザー*')

  return lines.join('\n')
}

// ──────────────────────────────────────────────
//  ChatGPT Image 2 Prompt
// ──────────────────────────────────────────────

export function generateChatGPTPrompt(analysis: GunplaAnalysis): string {
  const parts: string[] = []

  parts.push(
    `Create a highly detailed, photorealistic 3D render of a Gunpla model kit: ${analysis.kitName}.`,
  )
  parts.push('')

  parts.push('Color scheme based on expert paint analysis:')
  for (const block of analysis.blocks) {
    const topRec = block.recommendations[0]
    if (!topRec) continue
    const colorDesc = buildColorDesc(topRec)
    parts.push(`- ${block.blockName}: ${colorDesc}`)
  }

  parts.push('')
  parts.push(
    'Lighting: studio lighting with soft shadows, slight rim light to accentuate panel lines.',
  )
  parts.push(
    'Background: neutral dark gradient (near black). Camera: 3/4 front view, slight low angle.',
  )
  parts.push(
    'Details: panel line engravings visible, surface texture shows subtle metallic or matte finish, decals suggested.',
  )
  parts.push('Style: high-end scale model photography, sharp focus, 4K resolution.')

  return parts.join('\n')
}

function buildColorDesc(rec: PaintRecommendation): string {
  if (rec.type === 'change' && rec.from) {
    return `${rec.to.name} (${rec.to.hex}) — changed from ${rec.from.name}; ${rec.effect}`
  }
  if (rec.type === 'accent') {
    return `accent of ${rec.to.name} (${rec.to.hex}); ${rec.effect}`
  }
  return `${rec.to.name} (${rec.to.hex}); ${rec.effect}`
}

// ──────────────────────────────────────────────
//  PDF Download (html2canvas + jsPDF)
// ──────────────────────────────────────────────

export async function downloadPdf(elementId: string, filename: string): Promise<void> {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import('html2canvas'),
    import('jspdf'),
  ])

  const element = document.getElementById(elementId)
  if (!element) throw new Error(`Element #${elementId} not found`)

  const canvas = await html2canvas(element, {
    backgroundColor: '#0e0e18',
    scale: 2,
    useCORS: true,
    logging: false,
  })

  const imgData = canvas.toDataURL('image/png')
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 10
  const availWidth = pageWidth - margin * 2
  const imgHeight = (canvas.height * availWidth) / canvas.width

  let y = margin
  let remaining = imgHeight

  while (remaining > 0) {
    const sliceHeight = Math.min(remaining, pageHeight - margin * 2)

    pdf.addImage(
      imgData,
      'PNG',
      margin,
      y,
      availWidth,
      sliceHeight,
      undefined,
      'FAST',
      0,
    )

    remaining -= sliceHeight
    if (remaining > 0) {
      pdf.addPage()
      y = margin
    }

    // avoid infinite loop on zero
    if (sliceHeight === 0) break
  }

  pdf.save(filename)
}

// ──────────────────────────────────────────────
//  Clipboard helper
// ──────────────────────────────────────────────

export async function copyToClipboard(text: string): Promise<void> {
  await navigator.clipboard.writeText(text)
}

// ──────────────────────────────────────────────
//  File download helper
// ──────────────────────────────────────────────

export function downloadTextFile(text: string, filename: string): void {
  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
